### POST request to example server
POST {{host}}/api/feed
Content-Type: application/json

{
    "url": [
      "https://vercel.com/atom"
    ]
}

###
GET http://localhost:3000/api/feed/add?url=https://tailwindcss.com/feeds/feed.xml
